CREATE TABLE `data_platform_operations_item_data`
(
    `Operations`                               int(16) NOT NULL,
    `OperationsItem`                           int(6) NOT NULL,
	`SupplyChainRelationshipID`                int(16) NOT NULL,
	`SupplyChainRelationshipDeliveryID`        int(6) NOT NULL,
	`SupplyChainRelationshipDeliveryPlantID`   int(4) NOT NULL,
	`SupplyChainRelationshipProductionPlantID` int(4) NOT NULL,
    `Product`                                  varchar(40) NOT NULL,
    `Buyer`                                    int(12) NOT NULL,
    `Seller`                                   int(12) NOT NULL,
    `DeliverToParty`                           int(12) NOT NULL,
    `DeliverToPlant`                           varchar(4) NOT NULL,
    `DeliverFromParty`                         int(12) NOT NULL,
    `DeliverFromPlant`                         varchar(4) NOT NULL,
    `ProductionPlantBusinessPartner`           int(12) NOT NULL,
    `ProductionPlant`                          varchar(4) NOT NULL,
    `OperationsText`                           varchar(200) NOT NULL,
    `BillOfMaterial`                           int(16) DEFAULT NULL,
    `OperationsStatus`                         varchar(2) DEFAULT NULL,
    `ResponsiblePlannerGroup`                  varchar(3) DEFAULT NULL,
    `OperationsUnit`                           varchar(3) DEFAULT NULL,
    `StandardLotSizeQuantity`                  float(15) DEFAULT NULL,
    `MinimumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `MaximumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `PlainLongText`                            varchar(1000) DEFAULT NULL,
    `WorkCenter`                               int(16) DEFAULT NULL,
    `ValidityStartDate`                        date DEFAULT NULL,
    `ValidityEndDate`                          date DEFAULT NULL,
    `CreationDate`                             date NOT NULL,
    `LastChangeDate`                           date NOT NULL,
    `IsMarkedForDeletion`                      tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Operations`, `OperationsItem`),

    CONSTRAINT `DPFMOperationsItemData_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
    CONSTRAINT `DPFMOperationsItemDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DPFMOperationsItemDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
--     CONSTRAINT `DPFMOperationsItemDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
-- 	CONSTRAINT `DPFMOperationsItemDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_scr_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DPFMOperationsItemDataBOM_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DPFMOperationsItemDataOperationsUnit_fk` FOREIGN KEY (`OperationsUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMOperationsItemDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_general_data` (`WorkCenter`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
