CREATE TABLE `data_platform_operations_item_operation_data`
(
    `Operations`                               int(16) NOT NULL,
    `OperationsItem`                           int(6) NOT NULL,
    `OperationID`                              int(4) NOT NULL,
	`SupplyChainRelationshipID`                int(16) NOT NULL,
	`SupplyChainRelationshipDeliveryID`        int(6) NOT NULL,
	`SupplyChainRelationshipDeliveryPlantID`   int(4) NOT NULL,
	`SupplyChainRelationshipProductionPlantID` int(4) NOT NULL,
    `Product`                                  varchar(40) NOT NULL, 
    `Buyer`                                    int(12) NOT NULL,
    `Seller`                                   int(12) NOT NULL,
    `DeliverToParty`                           int(12) NOT NULL,
    `DeliverToPlant`                           varchar(4) NOT NULL,
    `DeliverFromParty`                         int(12) NOT NULL,
    `DeliverFromPlant`                         varchar(4) NOT NULL,
    `ProductionPlantBusinessPartner`           int(12) NOT NULL,
    `ProductionPlant`                          varchar(4) NOT NULL,
    `Sequence`                                 int(4) NOT NULL,
    `SequenceText`                             varchar(200) DEFAULT NULL,
    `OperationText`                            varchar(200) NOT NULL,
    `OperationStatus`                          varchar(2) DEFAULT NULL,
    `ResponsiblePlannerGroup`                  varchar(3) DEFAULT NULL,
    `OperationUnit`                            varchar(3) NOT NULL,
    `StandardLotSizeQuantity`                  float(15) DEFAULT NULL,
    `MinimumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `MaximumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `PlainLongText`                            varchar(1000) DEFAULT NULL,
    `WorkCenter`                               int(16) DEFAULT NULL,
    `CapacityCategoryCode`                     varchar(3) DEFAULT NULL,
    `OperationCostingRelevancyType`            varchar(1) DEFAULT NULL,
    `OperationSetupType`                       varchar(2) DEFAULT NULL,
    `OperationSetupGroupCategory`              varchar(10) DEFAULT NULL,
    `OperationSetupGroup`                      varchar(10) DEFAULT NULL,
    `OperationReferenceQuantity`               float(15) DEFAULT NULL,
    `MaximumWaitDuration`                      float(11) DEFAULT NULL,
    `StandardWaitDuration`                     float(11) DEFAULT NULL,
    `MinimumWaitDuration`                      float(11) DEFAULT NULL,
    `WaitDurationUnit`                         varchar(3) DEFAULT NULL,
    `MaximumQueueDuration`                     float(11) DEFAULT NULL,
    `StandardQueueDuration`                    float(11) DEFAULT NULL,
    `MinimumQueueDuration`                     float(11) DEFAULT NULL,
    `QueueDurationUnit`                        varchar(3) DEFAULT NULL,
    `MaximumMoveDuration`                      float(11) DEFAULT NULL,
    `StandardMoveDuration`                     float(11) DEFAULT NULL,
    `MinimumMoveDuration`                      float(11) DEFAULT NULL,
    `MoveDurationUnit`                         varchar(3) DEFAULT NULL,
    `StandardDeliveryDuration`                 float(11) DEFAULT NULL,
    `StandardDeliveryDurationUnit`             varchar(3) DEFAULT NULL,
    `StandardOperationScrapPercent`            float(7) DEFAULT NULL,
    `CostElement`                              varchar(10) DEFAULT NULL,
    `ValidityStartDate`                        date DEFAULT NULL,
    `ValidityEndDate`                          date DEFAULT NULL,
    `CreationDate`                             date NOT NULL,
    `LastChangeDate`                           date NOT NULL,
    `IsMarkedForDeletion`                      tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Operations`, `OperationsItem`, `OperationID`),

    CONSTRAINT `DataPlatformOperationsItemOperationData_fk` FOREIGN KEY (`Operations`, `OperationsItem`) REFERENCES `data_platform_operations_item_data` (`Operations`, `OperationsItem`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`, , `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
	CONSTRAINT `DataPlatformOperationsItemOperationDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_scr_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataOperationUnit_fk` FOREIGN KEY (`OperationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_general_data` (`WorkCenter`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataWaitDurationUnit_fk` FOREIGN KEY (`WaitDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataQueueDurationUnit_fk` FOREIGN KEY (`QueueDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataMoveDurationUnit_fk` FOREIGN KEY (`MoveDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataStandardDeliveryDurationUnit_fk` FOREIGN KEY (`StandardDeliveryDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
