CREATE TABLE `data_platform_operations_item_data`
(
    `Operations`                       int(16) NOT NULL,
    `OperationsItem`                   int(6) NOT NULL,
    `Sequence`                         int(4) NOT NULL,
    `Product`                          varchar(40) NOT NULL, 
    `BusinessPartner`                  int(12) NOT NULL,
    `Plant`                            varchar(4) NOT NULL,
    `OperationsText`                   varchar(200) DEFAULT NULL,
    `SequenceText`                     varchar(200) DEFAULT NULL,
    `OperationsStatus`                 varchar(2) DEFAULT NULL,
    `ResponsiblePlannerGroup`          varchar(3) DEFAULT NULL,
    `ValidityStartDate`                date DEFAULT NULL,
    `ValidityEndDate`                  date DEFAULT NULL,
    `StandardLotSizeQuantity`          float(15) DEFAULT NULL,
    `MinimumLotSizeQuantity`           float(15) DEFAULT NULL,
    `MaximumLotSizeQuantity`           float(15) DEFAULT NULL,
    `OperationsUnit`                   varchar(3) DEFAULT NULL,
    `CreationDate`                     date DEFAULT NULL,
    `LastChangeDate`                   date DEFAULT NULL,
    `PlainLongText`                    varchar(1000) DEFAULT NULL,
    `WorkCenterTypeCode`               varchar(2) DEFAULT NULL,
    `WorkCenterInternalID`             varchar(8) DEFAULT NULL,
    `CapacityCategoryCode`             varchar(3) DEFAULT NULL,
    `OperationCostingRelevancyType`    varchar(1) DEFAULT NULL,
    `NumberOfTimeTickets`              varchar(4) DEFAULT NULL,
    `NumberOfConfirmationSlips`        varchar(3) DEFAULT NULL,
    `OperationSetupType`               varchar(2) DEFAULT NULL,
    `OperationSetupGroupCategory`      varchar(10) DEFAULT NULL,
    `OperationSetupGroup`              varchar(10) DEFAULT NULL,
    `OperationReferenceQuantity`       float(15) DEFAULT NULL,
    `OpQtyToBaseQtyNmrtr`              float(6) DEFAULT NULL,
    `OpQtyToBaseQtyDnmntr`             float(6) DEFAULT NULL,
    `MaximumWaitDuration`              float(11) DEFAULT NULL,
    `MaximumWaitDurationUnit`          varchar(3) DEFAULT NULL,
    `MinimumWaitDuration`              float(11) DEFAULT NULL,
    `MinimumWaitDurationUnit`          varchar(3) DEFAULT NULL,
    `StandardQueueDuration`            float(11) DEFAULT NULL,
    `StandardQueueDurationUnit`        varchar(3) DEFAULT NULL,
    `MinimumQueueDuration`             float(11) DEFAULT NULL,
    `MinimumQueueDurationUnit`         varchar(3) DEFAULT NULL,
    `StandardMoveDuration`             float(11) DEFAULT NULL,
    `StandardMoveDurationUnit`         varchar(3) DEFAULT NULL,
    `MinimumMoveDuration`              float(11) DEFAULT NULL,
    `MinimumMoveDurationUnit`          varchar(3) DEFAULT NULL,
    `OpIsExtlyProcdWithSubcontrg`      tinyint(1) DEFAULT NULL,
    `PlannedDeliveryDuration`          int(4) DEFAULT NULL,
    `Seller`                           int(12) DEFAULT NULL,
    `NumberOfOperationPriceUnits`      int(6) DEFAULT NULL,
    `CostElement`                      varchar(10) DEFAULT NULL,
    `OpExternalProcessingPrice`        float(13) DEFAULT NULL,
    `OpExternalProcessingCurrency`     varchar(5) DEFAULT NULL,
    `OperationScrapPercent`            float(7) DEFAULT NULL,
    `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Operations`, `OperationsItem`),

    CONSTRAINT `DataPlatformOperationsItemData_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
    CONSTRAINT `DataPlatformOperationsItemDataProduct_fk` FOREIGN KEY (`Product`, `BusinessPartner`, `Plant`) REFERENCES `data_platform_product_master_bp_plant_data` (`Product`, `BusinessPartner`, `Plant`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
  