CREATE TABLE `data_platform_operations_item_operation_data`
(
    `Operations`                               int(16) NOT NULL,
    `OperationsItem`                           int(6) NOT NULL,
    `OperationID`                              int(4) NOT NULL,
	`SupplyChainRelationshipID`                int(16) NOT NULL,
	`SupplyChainRelationshipDeliveryID`        int(6) NOT NULL,
	`SupplyChainRelationshipDeliveryPlantID`   int(4) NOT NULL,
	`SupplyChainRelationshipProductionPlantID` int(4) NOT NULL,
    `Product`                                  varchar(40) NOT NULL, 
    `Buyer`                                    int(12) NOT NULL,
    `Seller`                                   int(12) NOT NULL,
    `DeliverFromParty`                         int(12) NOT NULL,
    `DeliverFromPlant`                         varchar(4) NOT NULL,
    `DeliverToParty`                           int(12) NOT NULL,
    `DeliverToPlant`                           varchar(4) NOT NULL,
    `Sequence`                                 int(4) NOT NULL,
    `ProductionPlantBusinessPartner`           int(12) NOT NULL,
    `ProductionPlant`                          varchar(4) NOT NULL,
    `OperationText`                            varchar(200) NOT NULL,
    `ValidityStartDate`                        date DEFAULT NULL,
    `ValidityEndDate`                          date DEFAULT NULL,
    `SequenceText`                             varchar(200) DEFAULT NULL,
    `OperationStatus`                          varchar(2) DEFAULT NULL,
    `ResponsiblePlannerGroup`                  varchar(3) DEFAULT NULL,
    `StandardLotSizeQuantity`                  float(15) DEFAULT NULL,
    `MinimumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `MaximumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `OperationUnit`                            varchar(3) NOT NULL,
    `CreationDate`                             date DEFAULT NULL,
    `LastChangeDate`                           date DEFAULT NULL,
    `PlainLongText`                            varchar(1000) DEFAULT NULL,
    `WorkCenter`                               int(16) DEFAULT NULL,
    `CapacityCategoryCode`                     varchar(3) DEFAULT NULL,
    `OperationCostingRelevancyType`            varchar(1) DEFAULT NULL,
    `NumberOfTimeTickets`                      varchar(4) DEFAULT NULL,
    `NumberOfConfirmationSlips`                varchar(3) DEFAULT NULL,
    `OperationSetupType`                       varchar(2) DEFAULT NULL,
    `OperationSetupGroupCategory`              varchar(10) DEFAULT NULL,
    `OperationSetupGroup`                      varchar(10) DEFAULT NULL,
    `OperationReferenceQuantity`               float(15) DEFAULT NULL,
    `OpQtyToBaseQtyNmrtr`                      float(6) DEFAULT NULL,
    `OpQtyToBaseQtyDnmntr`                     float(6) DEFAULT NULL,
    `MaximumWaitDuration`                      float(11) DEFAULT NULL,
    `MaximumWaitDurationUnit`                  varchar(3) DEFAULT NULL,
    `MinimumWaitDuration`                      float(11) DEFAULT NULL,
    `MinimumWaitDurationUnit`                  varchar(3) DEFAULT NULL,
    `StandardQueueDuration`                    float(11) DEFAULT NULL,
    `StandardQueueDurationUnit`                varchar(3) DEFAULT NULL,
    `MinimumQueueDuration`                     float(11) DEFAULT NULL,
    `MinimumQueueDurationUnit`                 varchar(3) DEFAULT NULL,
    `StandardMoveDuration`                     float(11) DEFAULT NULL,
    `StandardMoveDurationUnit`                 varchar(3) DEFAULT NULL,
    `MinimumMoveDuration`                      float(11) DEFAULT NULL,
    `MinimumMoveDurationUnit`                  varchar(3) DEFAULT NULL,
    `OpIsExtlyProcdWithSubcontrg`              tinyint(1) DEFAULT NULL,
    `PlannedDeliveryDuration`                  int(4) DEFAULT NULL,
    `NumberOfOperationPriceUnits`              int(6) DEFAULT NULL,
    `CostElement`                              varchar(10) DEFAULT NULL,
    `OperationScrapPercent`                    float(7) DEFAULT NULL,
    `IsMarkedForDeletion`                      tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Operations`, `OperationsItem`, `OperationID`),

    CONSTRAINT `DataPlatformOperationsItemOperationData_fk` FOREIGN KEY (`Operations`, `OperationsItem`) REFERENCES `data_platform_operations_item_data` (`Operations`, `OperationsItem`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_supply_chain_relationship_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_supply_chain_relationship_delivery_relation_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`, , `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
	CONSTRAINT `DataPlatformOperationsItemOperationDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataOperationUnit_fk` FOREIGN KEY (`OperationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformOperationsItemOperationDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_general_data` (`WorkCenter`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
  